version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-storage
    ports:
      - "9000:9000"      # API port
      - "9001:9001"      # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: myapp-storage
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - storage-network

  # Optional: MinIO Client for easy management
  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin; do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/myapp-storage --ignore-existing;
      /usr/bin/mc policy set public minio/myapp-storage;
      tail -f /dev/null
      "
    networks:
      - storage-network

volumes:
  minio_data:
    driver: local

networks:
  storage-network:
    driver: bridge
